Hiflylabs/awesome-dbt

README.md
Great initiative, I love this repo!
=> Added utilities that I use and Elementary 

README.md
I'm affiliated with three dbt-related projects, and I think they're awesome. Please let me know if you have any questions
=> Add sqlfmt, Privacy Dynamics, and dbt-privacy

README.md
Add dbt example project, article on self-service, new BI tool, and dbt-date package
=> Add FlexIt Analytics and more

README.md
- Analytics engineering glossary
- Utilities: dbtenv, docs to notion
- Packages: dbt_constraints
- Community: Atlan newsletter, conferences notion, and data council 2022
=> Add resources discovered lately

README.md
Happy to contribute my tutorial about this dbt Metrics integration.
=> Add Cube to Integrations

README.md
Thank you for your repository. I think that some people have a demand for aws-athena though, there is no example. Therefore, I added an example of how to start dbt with aws-athena.
Thank you in advance
=> add sample for dbt-athena

README.md
Add a series of 5 posts that illustrate how to develop data projects with dbt on AWS.
=> Add dbt on AWS series

README.md
Add Towards Data Science article about how dbt can enable semantic-free BI
=> Add Semantic-free user story

README.md
=> update dbt on aws with permanent links

README.md
Hi there, I'm looking to add my paid Udemy course on to the list of resources. Appreciate if the answer is no given that it's my own course!
My editor also seems to have trimmed some trailing whitespace.
=> Adding Udemy course to the list of courses

.github/workflows/check_links.yml, README.md
- Added awesome_bot to validate the links for the resources.
- Removed the stale resources (e.g. dbtlearn.com).
- Updated the URLs when necessary.
_NB_: make sure to squash this PR.
=> Audit contents

README.md
Added link to https://github.com/datarootsio/dbt-fabric
=> add dbt-fabric

README.md
Adding a link to this blog article: https://docs.getdbt.com/blog/kimball-dimensional-model
=> How to Create Kimball Dimensional Models

README.md
Add resources
- modal-dbt
- Speeding up the dbt™ docs by 20x with React Server Components
- How to Create CI/CD Pipelines for dbt Core
- Turntable VSCode extension
- dbt-loom
- dbt-fake
- dbt_cloud_run_cost
- dbt-reconfigured
- awesome-public-dbt-projects
- mdsinabox
- gee_production_gatekeepers
- dbt-beyond-the-basics
- mdsfest-opensource-mds
=> Sync Resources

README.md
adding the timescale-dbt adapter created by @sdebruyn
=> add timescaledb

README.md
=> Add Tabula

README.md
Add 
- datapilot
- dbt-sreamdeck
=> Extend list

README.md
It's a good resource if someone starts with dbt and redshift. Includes many Redshift specific optimizations that can be useful for anyone on AWS
=> Add link to best pracices with AWS Redshift

README.md
=> add make open data

README.md
Adding [dbt-beyond-the-basics](https://github.com/pgoslatara/dbt-beyond-the-basics), a dbt project I maintain that showcases some advanced features that can be used in CI for dbt projects and contains an extensive README that details these features.
=> Adding dbt-beyond-the-basics

README.md
Adding a GitHub action that I've created to download artifacts from dbt Cloud CI jobs.
=> Adding dbt-cloud-download-artifacts-action

README.md
With Fabric gaining traction, these seem to be missing here.
=> Adding dbt-fabrickspark and dbt-fabricksparknb

README.md
I've recently been working on this plugin: https://github.com/ramonvermeulen/dbt-toolkit
Might be a nice addition to the list of dbt utilities.
=> feat: add dbt-toolkit to list of utilities

README.md
PipeRider has been superseded by Recce.
issue : https://github.com/Hiflylabs/awesome-dbt/issues/103
=> remove piperider
